---

- name: Pause for 5 seconds in Recursive mode
  ansible.builtin.pause:
    seconds: 5
  when: RECURSIVE_MONITORING | default(False)

- name: Set API URL
  set_fact:
    dls_api_url: "{{ dls_api_url_from_env }}"
  when:
    - dls_api_url_from_env is defined
    - dls_api_url_from_env | length > 0

- name: Get DAG RUN info from Airflow
  uri:
    url: "{{ dls_api_url }}/dags/{{ dag_id }}/dagRuns/{{ TOSCA_JOB_ID }}"
    url_username: "{{ dls_api_username }}"
    url_password: "{{ dls_api_password }}"
    force_basic_auth: yes
    method: GET
    headers:
      Accept: application/json
    return_content: yes
  register: get_response
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Extract content
  set_fact:
    content: "{{ get_response.content | from_json }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Extract TOSCA_JOB_STATUS
  set_fact:
    TOSCA_JOB_STATUS: "{{ content.state | upper }}"

- name: Fix TOSCA_JOB_STATUS for success
  set_fact:
    TOSCA_JOB_STATUS: "COMPLETED"
  when:
    - TOSCA_JOB_STATUS == "SUCCESS"

- name: Recursive call to "monitor_dag_tasks.yaml"
  include_tasks: "monitor_dag_tasks.yaml"
  when:
    - RECURSIVE_MONITORING | default(False)
    - TOSCA_JOB_STATUS != 'COMPLETED' and TOSCA_JOB_STATUS != 'FAILED'
