- name: Submit DAG RUN to Airflow
  hosts: all
  tasks:

    - name: Set submit tasks file
      set_fact:
        submit_tasks_file: "{{ submit_tasks }}"
        execution_url: ""

    - name: Submit DAG RUN to Airflow
      include_tasks: "{{ submit_tasks_file }}"
