- name: Submit DAG RUN to Airflow
  hosts: all
  strategy: free
  tasks:
    - name: Set oid
      set_fact:
        oid: "{{ oid_input }}"
      when:
        - oid_input is defined
        - oid_input | length > 0

    - name: Set target_path
      set_fact:
        target_path: "{{ target_path_input }}"
      when:
        - target_path_input is defined
        - target_path_input | length > 0

    - name: Set target conf
      set_fact:
        target_conf:
          oid: "{{ oid }}"
          target: "{{ target_path }}"
          connection: "{{ connection }}"

    - name: add extra_conf
      set_fact:
        target_conf: "{{ conf | from_json | combine(target_conf) }}"
      when:
        - conf is defined
        - conf | length > 0

    - name: Set request body
      set_fact:
        request_body:
          conf: "{{ target_conf }}"

    - name: Submit DAG RUN to Airflow
      uri:
        url: "{{ dls_api_url }}/dags/{{ dag_id }}/dagRuns"
        url_username: "{{ dls_api_username }}"
        url_password: "{{ dls_api_password }}"
        force_basic_auth: yes
        method: POST
        body: "{{ request_body | to_json }}"
        headers:
          Content-Type: application/json
          Accept: application/json
        return_content: yes
      register: submission_response

    - name: Extract content
      set_fact:
        content: "{{ submission_response.content | from_json }}"

    - name: Extract TOSCA_JOB_ID
      set_fact:
        TOSCA_JOB_ID: "{{ content.dag_run_id }}"
