---
- name: Set API URL
  set_fact:
    dls_api_url: "{{ dls_api_url_from_env }}"
  when:
    - dls_api_url_from_env is defined
    - dls_api_url_from_env | length > 0

- name: Submit DAG RUN to Airflow
  uri:
    url: "{{ dls_api_url }}/dags/{{ dag_id }}/dagRuns"
    url_username: "{{ dls_api_username }}"
    url_password: "{{ dls_api_password }}"
    force_basic_auth: yes
    method: POST
    body: "{{ request_body | to_json }}"
    headers:
      Content-Type: application/json
      Accept: application/json
    return_content: yes
  register: submission_response
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Extract content
  set_fact:
    content: "{{ submission_response.content | from_json }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Extract TOSCA_JOB_ID
  set_fact:
    TOSCA_JOB_ID: "{{ content.dag_run_id }}"
