---

- name: Set login
  set_fact:
    login: "{{ login_input }}"
  when:
    - login_input is defined
    - login_input | length > 0

- name: Set vault_id
  set_fact:
    vault_id: "{{ vault_id_input }}"
  when:
    - vault_id_input is defined
    - vault_id_input | length > 0

- name: Set target conf
  set_fact:
    target_conf:
      login: "{{ login }}"
      vault_id: "{{ vault_id }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Set request body
  set_fact:
    request_body:
      conf: "{{ conf | default('{}') | from_json | combine(target_conf) }}"
  no_log: True

- name: Import Submit DAG RUN to Airflow
  include_tasks: submit_tasks.yaml
