---
- name: Set host from env
  set_fact:
    host: "{{ host_from_env }}"
  when:
    - host_from_env is defined
    - host_from_env | length > 0

- name: Set location
  set_fact:
    location: "{{ location_input }}"
  when:
    - location_input is defined
    - location_input | length > 0

- name: Set experiment
  set_fact:
    experiment: "{{ experiment_input }}"
  when:
    - experiment_input is defined
    - experiment_input | length > 0

- name: Set model_path
  set_fact:
    model_path: "{{ model_path_input }}"
  when:
    - model_path_input is defined
    - model_path_input | length > 0

- name: Set login
  set_fact:
    login: "{{ login_input }}"
  when:
    - login_input is defined
    - login_input | length > 0

- name: Set vault_id
  set_fact:
    vault_id: "{{ vault_id_input }}"
  when:
    - vault_id_input is defined
    - vault_id_input | length > 0

- name: Set target conf
  set_fact:
    target_conf:
      location: "{{ location }}"
      mlflow_runid: "{{ experiment }}"
      mlflow_modelpath: "{{ model_path }}"
      host: "{{ host }}"
      login: "{{ login }}"
      vault_id: "{{ vault_id }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"


- name: add extra_conf
  set_fact:
    target_conf: "{{ conf | from_json | combine(target_conf) }}"
  when:
    - conf is defined
    - conf | length > 0
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Set request body
  set_fact:
    request_body:
      dag_run_id: "{{ login }}-{{ 1000000000 | random | to_uuid }}"
      conf: "{{ target_conf }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Import Submit DAG RUN to Airflow
  include_tasks: submit_tasks.yaml
