- name: Submit DAG RUN to Airflow
  hosts: all
  strategy: free
  tasks:

    - name: Set image_id
      set_fact:
        image_id: "{{ image_id_input }}"
      when:
        - image_id_input is defined
        - image_id_input | length > 0

    - name: Set image_id from file name
      set_fact:
        image_id: "{{ builded_file_name }}"
      when:
        - builded_file_name is defined
        - builded_file_name | length > 0

    - name: Set target_path
      set_fact:
        target_path: "{{ target_path_input }}"
      when:
        - target_path_input is defined
        - target_path_input | length > 0

    - name: Set login
      set_fact:
        login: "{{ login_input }}"
      when:
        - login_input is defined
        - login_input | length > 0

    - name: Set vault_id
      set_fact:
        vault_id: "{{ vault_id_input }}"
      when:
        - vault_id_input is defined
        - vault_id_input | length > 0

    - name: Set target conf
      set_fact:
        target_conf:
          image_id: "{{ image_id }}"
          target: "{{ target_path }}"
          host: "{{ host }}"
          port: "{{ port }}"
          login: "{{ login }}"
          vault_id: "{{ vault_id }}"
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: add extra_conf
      set_fact:
        target_conf: "{{ conf | from_json | combine(target_conf) }}"
      when:
        - conf is defined
        - conf | length > 0
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: Set request body
      set_fact:
        request_body:
          conf: "{{ target_conf }}"
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: Import Submit DAG RUN to Airflow
      import_tasks: submit_tasks.yaml

    - name: Set Image path
      set_fact:
        image_file_path: "{{ target_path }}/{{ image_id }}"
