- name: Submit DAG RUN to Airflow
  hosts: all
  strategy: free
  tasks:
    - name: Set oid
      set_fact:
        oid: "{{ oid_input }}"
      when:
        - oid_input is defined
        - oid_input | length > 0

    - name: Set target_path
      set_fact:
        target_path: "{{ target_path_input }}"
      when:
        - target_path_input is defined
        - target_path_input | length > 0

    - name: Set target conf
      set_fact:
        target_conf:
          oid: "{{ oid }}"
          target: "{{ target_path }}"
          host: "{{ host }}"
          port: "{{ port }}"
          login: "{{ login }}"
          vault_id: "{{ vault_id }}"
      no_log: "{{ debug_logs | default('false') == 'false' }}"


    - name: add extra_conf
      set_fact:
        target_conf: "{{ conf | from_json | combine(target_conf) }}"
      when:
        - conf is defined
        - conf | length > 0
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: Set request body
      set_fact:
        request_body:
          conf: "{{ target_conf }}"
      no_log: "{{ debug_logs | default('false') == 'false' }}"

    - name: Import Submit DAG RUN to Airflow
      import_tasks: submit_tasks.yaml
