---
- name: Set host from env
  set_fact:
    host: "{{ host_from_env }}"
  when:
    - host_from_env is defined
    - host_from_env | length > 0

- name: Set mid
  set_fact:
    mid: "{{ mid_input }}"
  when:
    - mid_input is defined
    - mid_input | length > 0

- name: Set source_path
  set_fact:
    source_path: "{{ source_path_input }}"
  when:
    - source_path_input is defined
    - source_path_input | length > 0

- name: Set register
  set_fact:
    register: "{{ register_input }}"
  when:
    - register_input is defined
    - register_input | length > 0

- name: Set login
  set_fact:
    login: "{{ login_input }}"
  when:
    - login_input is defined
    - login_input | length > 0

- name: Set vault_id
  set_fact:
    vault_id: "{{ vault_id_input }}"
  when:
    - vault_id_input is defined
    - vault_id_input | length > 0

- name: Set target conf
  set_fact:
    target_conf:
      mid: "{{ mid }}"
      source: "{{ source_path }}"
      host: "{{ host }}"
      port: "{{ port | int }}"
      login: "{{ login }}"
      vault_id: "{{ vault_id }}"
      register: "{{ register | bool }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"


- name: add extra_conf
  set_fact:
    target_conf: "{{ conf | from_json | combine(target_conf) }}"
  when:
    - conf is defined
    - conf | length > 0
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Set request body
  set_fact:
    request_body:
      dag_run_id: "{{ login }}-{{ 1000000000 | random | to_uuid }}"
      conf: "{{ target_conf }}"
  no_log: "{{ debug_logs | default('false') == 'false' }}"

- name: Import Submit DAG RUN to Airflow
  include_tasks: submit_tasks.yaml
